// app/layout.tsx
"use client";

import "./globals.css";
import { CacheProvider } from "@chakra-ui/next-js";
import { ChakraProvider } from "@chakra-ui/react";
import { extendTheme } from "@chakra-ui/react";
import PortfolioTheme from "./theme/PortfolioTheme";
import Header from "./components/Header";
import Footer from "./components/Footer";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// 1. Import the extendTheme function

// 2. Extend the theme to include custom colors, fonts, etc

const colors = {
  brand: {
    900: "#1a365d",
    800: "#153e75",
    700: "#2a69ac",
  },
};

const theme = extendTheme({ colors });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <head /> */}
      <body>
        <CacheProvider>
          <ChakraProvider theme={theme}>
            <Header />
            {children}
            <Footer />
          </ChakraProvider>
        </CacheProvider>
      </body>
    </html>
  );
}
