import * as GrIcons from "react-icons/gr";
import * as DiIcons from "react-icons/di";
import * as SiIcons from "react-icons/si";
import * as TbIcons from "react-icons/tb";
import * as BsIcons from "react-icons/bs";

export const stacks = [
  {
    // IconName: reactLogo,
    reactIcon: [SiIcons.SiReact, SiIcons.SiExpo],
    tickerName: "React /Native",
    name: "React Native",
    color: "#60DBFA",
    category: "hero+stack",
    level: "Very Good",
    content: "My main stack",
    project: "example",
  },
  {
    // IconName: reactLogo,
    reactIcon: [SiIcons.SiJavascript],
    tickerName: "Javascript",
    name: "JavaScript",
    color: "#60DBFA",
    category: "hero+stack",
    level: "Very Good",
    content: "My main stack, I did use pure JS in my work",
    project: "example",
  },
  {
    // IconName: reactLogo,
    reactIcon: [SiIcons.SiNodedotjs],
    tickerName: "Node.js",
    name: "NodeJs",
    color: "#60DBFA",
    category: "hero+stack",
    level: "Good",
    content: "What I use for my backend",
    project: "example",
  },
  {
    // IconName: reactLogo,
    reactIcon: [SiIcons.SiTypescript],
    tickerName: "TypeScript",
    name: "TypeScript",
    color: "#60DBFA",
    category: "",
    level: "beginner",
    content: "Still learning, this portfolio is in TS",
    project: "example",
  },
  {
    // IconName: reactLogo,
    reactIcon: [SiIcons.SiExpress],
    tickerName: "Express",
    name: "Express",
    color: "#60DBFA",
    category: "",
    level: "Good",
    content: "What I use for my backend, building REST APIs",
    project: "link",
  },
  {
    // IconName: GraphQLLogo,
    reactIcon: [SiIcons.SiGraphql],
    tickerName: "GraphQL",
    name: "GraphQl",
    color: "#B054AE",
    category: "hero+stack",
    level: "Good",
    content: "Mostly used in congunction with Amplify",
    project: "link",
  },
  {
    // IconName: GraphQLLogo,
    reactIcon: [SiIcons.SiPuppeteer],
    tickerName: "Puppeteer",
    name: "Puppet teer",
    color: "#B054AE",
    category: "hero+stack",
    level: "Good",
    content: "Used for making bots, scraping",
  },
  {
    // IconName: mongodb,
    reactIcon: [SiIcons.SiMongodb],
    tickerName: "MongoDB",
    color: "#59AA51",
    category: "hero+stack",
    level: "Good",
    content: "Building databases, unsued for sometimes",
    project: "link",
  },
  {
    // IconName: AWSLogo,
    reactIcon: [SiIcons.SiAmazonaws, SiIcons.SiAwsamplify],
    tickerName: "AWS",
    color: "#F2982C",
    category: "hero+stack",
    level: "Average",
    content: "learnt GraphQL Amplify, DynamoDB S3 Cognito, and Linux EC2",
    project: "link",
  },
  {
    // IconName: nextRoundBlue,
    reactIcon: [TbIcons.TbBrandNextjs],
    tickerName: "Next.js",
    color: "#74D4CF",
    category: "",
    level: "Okay",
    content:
      "This portfolio and youtube bot, are built with Next 13, Nice to have in same project the front, and back end",
    project: "example",
  },
  {
    // IconName: reactMotion2,
    reactIcon: [TbIcons.TbBrandFramerMotion],
    tickerName: "Framer Motion",
    name: "Framer Motion",
    color: "#7354C4",
    category: "hero+package",
    level: "Average",
    content: "Very handy for animations",
    project: "example",
  },

  //~~~~~~~~~~~UIs~~~~~~~~~~~~~~
  {
    reactIcon: [SiIcons.SiSemanticuireact],
    tickerName: "Semantic UI",
    name: "Semantic UI",
    category: "UI",
    level: "Very Good",
    content: "I used it for my first work, also easy to use",
    project: "example",
  },
  {
    reactIcon: [BsIcons.BsBootstrap],
    tickerName: "Bootstrap",
    name: "Bootstrap",
    category: "UI",
    level: "Beginner",
    content: "used when I don't care about css",
    project: "example",
  },
  {
    // IconName: reactLogo,
    reactIcon: [SiIcons.SiExpo],
    tickerName: "React Native Expo",

    name: "Expo",
    color: "#60DBFA",
    category: "UI",
    level: "Good",
    content: "For building mobile apps, with React Native",
    project: "example",
  },
  {
    reactIcon: [SiIcons.SiChakraui],
    tickerName: "Chakra UI",
    name: "ChakraUI",
    category: "UI",
    level: "Good",
    content:
      "Fast Learning curve, can use almost any CSS as props, not the prettiest",
    project: "example",
  },
  {
    reactIcon: [SiIcons.SiMui],
    tickerName: "MUI (Material UI)",
    name: "MaterialUI",
    category: "UI",
    level: "Average",
    content: "Pretty, but not the fastest to understand",
    project: "example",
  },
];
